### PR TITLE
show user name when downloading favorites

### PR DESCRIPTION
**Pull request by afterdelight**
show user name when downloading from favorites to make it more clear

### CODE REVIEW

**Comment by AlphaSlayer1964** [comment]
Improper formatting

**Comment by afterdelight** [comment]
what do you mean by that

**Comment by afterdelight** [comment]
i added \n so i can see the username more clearly. too many lines

**Comment by AlphaSlayer1964** [comment]
It will now print the username for any passed url or favorites 376c8ee

**Pull request closed without merging**
